/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppInfo {
  'id' : number,
  'name' : string,
  'description' : string,
}
export interface FileMetadata {
  'url' : string,
  'name' : string,
  'size' : bigint,
  'mimeType' : string,
  'uploadedAt' : bigint,
}
export interface FileMetadataInput {
  'url' : string,
  'name' : string,
  'size' : bigint,
  'mimeType' : string,
}
export interface FileNodeView {
  'id' : number,
  'content' : string,
  'name' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'parentId' : [] | [number],
  'nodeType' : FileType,
}
export type FileType = { 'file' : null } |
  { 'folder' : null };
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpResponse {
  'body' : string,
  'headers' : Array<HttpHeader>,
  'statusCode' : number,
}
export interface PermissionGrantView {
  'permissions' : Array<string>,
  'grantedAt' : bigint,
  'appId' : number,
}
export interface PermissionUpdateRequest {
  'permissions' : Array<string>,
  'appId' : number,
}
export interface ProcessSummary {
  'startTime' : bigint,
  'appId' : number,
  'appName' : string,
  'memoryUsage' : bigint,
  'cyclesUsed' : [] | [bigint],
}
export interface SystemStats {
  'osVersion' : string,
  'simulatedCyclesBalance' : bigint,
  'totalInstalledApps' : bigint,
  'systemTime' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'id' : Principal,
  'username' : string,
  'displayName' : string,
  'createdAt' : bigint,
  'darkMode' : boolean,
  'cycles' : bigint,
  'updatedAt' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createApp' : ActorMethod<[string, string], number>,
  'createFile' : ActorMethod<[string, string, [] | [number]], number>,
  'createFolder' : ActorMethod<[string, [] | [number]], number>,
  'deleteFileByUrl' : ActorMethod<[string], undefined>,
  'deleteNode' : ActorMethod<[number], undefined>,
  'fetchUrl' : ActorMethod<[string], HttpResponse>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCyclesBalance' : ActorMethod<[], bigint>,
  'getFileMetadata' : ActorMethod<[], Array<FileMetadata>>,
  'getGrantedPermissions' : ActorMethod<[number], Array<string>>,
  'getOSVersion' : ActorMethod<[], string>,
  'getPrincipalAsText' : ActorMethod<[], string>,
  'getSystemStats' : ActorMethod<[], SystemStats>,
  'getSystemTime' : ActorMethod<[], bigint>,
  'getTotalStorageBytesUsed' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantPermissions' : ActorMethod<[PermissionUpdateRequest], undefined>,
  'installApp' : ActorMethod<[number], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'kvDelete' : ActorMethod<[string], undefined>,
  'kvGet' : ActorMethod<[string], [] | [string]>,
  'kvKeys' : ActorMethod<[], Array<string>>,
  'kvSet' : ActorMethod<[string, string], undefined>,
  'listAllGrantedPermissions' : ActorMethod<[], Array<PermissionGrantView>>,
  'listAvailableApps' : ActorMethod<[], Array<AppInfo>>,
  'listChildren' : ActorMethod<[[] | [number]], Array<FileNodeView>>,
  'listRunningProcesses' : ActorMethod<[Uint32Array], Array<ProcessSummary>>,
  'listUserInstalledApps' : ActorMethod<[], Array<AppInfo>>,
  'readFile' : ActorMethod<[number], string>,
  'revokePermissions' : ActorMethod<[number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveFileMetadata' : ActorMethod<[FileMetadataInput], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'uninstallApp' : ActorMethod<[number], undefined>,
  'updateFileContent' : ActorMethod<[number, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];