/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpResponse = IDL.Record({
  'body' : IDL.Text,
  'headers' : IDL.Vec(HttpHeader),
  'statusCode' : IDL.Nat16,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : IDL.Int,
  'darkMode' : IDL.Bool,
  'cycles' : IDL.Nat,
  'updatedAt' : IDL.Int,
});
export const FileMetadata = IDL.Record({
  'url' : IDL.Text,
  'name' : IDL.Text,
  'size' : IDL.Nat,
  'mimeType' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const SystemStats = IDL.Record({
  'osVersion' : IDL.Text,
  'simulatedCyclesBalance' : IDL.Nat,
  'totalInstalledApps' : IDL.Nat,
  'systemTime' : IDL.Int,
});
export const PermissionUpdateRequest = IDL.Record({
  'permissions' : IDL.Vec(IDL.Text),
  'appId' : IDL.Nat32,
});
export const PermissionGrantView = IDL.Record({
  'permissions' : IDL.Vec(IDL.Text),
  'grantedAt' : IDL.Int,
  'appId' : IDL.Nat32,
});
export const AppInfo = IDL.Record({
  'id' : IDL.Nat32,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const FileType = IDL.Variant({ 'file' : IDL.Null, 'folder' : IDL.Null });
export const FileNodeView = IDL.Record({
  'id' : IDL.Nat32,
  'content' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'parentId' : IDL.Opt(IDL.Nat32),
  'nodeType' : FileType,
});
export const ProcessSummary = IDL.Record({
  'startTime' : IDL.Int,
  'appId' : IDL.Nat32,
  'appName' : IDL.Text,
  'memoryUsage' : IDL.Nat,
  'cyclesUsed' : IDL.Opt(IDL.Nat),
});
export const FileMetadataInput = IDL.Record({
  'url' : IDL.Text,
  'name' : IDL.Text,
  'size' : IDL.Nat,
  'mimeType' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createApp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat32], []),
  'createFile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat32)],
      [IDL.Nat32],
      [],
    ),
  'createFolder' : IDL.Func([IDL.Text, IDL.Opt(IDL.Nat32)], [IDL.Nat32], []),
  'deleteFileByUrl' : IDL.Func([IDL.Text], [], []),
  'deleteNode' : IDL.Func([IDL.Nat32], [], []),
  'fetchUrl' : IDL.Func([IDL.Text], [HttpResponse], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCyclesBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getFileMetadata' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
  'getGrantedPermissions' : IDL.Func(
      [IDL.Nat32],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getOSVersion' : IDL.Func([], [IDL.Text], ['query']),
  'getPrincipalAsText' : IDL.Func([], [IDL.Text], ['query']),
  'getSystemStats' : IDL.Func([], [SystemStats], ['query']),
  'getSystemTime' : IDL.Func([], [IDL.Int], ['query']),
  'getTotalStorageBytesUsed' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantPermissions' : IDL.Func([PermissionUpdateRequest], [], []),
  'installApp' : IDL.Func([IDL.Nat32], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'kvDelete' : IDL.Func([IDL.Text], [], []),
  'kvGet' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'kvKeys' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'kvSet' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'listAllGrantedPermissions' : IDL.Func(
      [],
      [IDL.Vec(PermissionGrantView)],
      ['query'],
    ),
  'listAvailableApps' : IDL.Func([], [IDL.Vec(AppInfo)], ['query']),
  'listChildren' : IDL.Func(
      [IDL.Opt(IDL.Nat32)],
      [IDL.Vec(FileNodeView)],
      ['query'],
    ),
  'listRunningProcesses' : IDL.Func(
      [IDL.Vec(IDL.Nat32)],
      [IDL.Vec(ProcessSummary)],
      ['query'],
    ),
  'listUserInstalledApps' : IDL.Func([], [IDL.Vec(AppInfo)], ['query']),
  'readFile' : IDL.Func([IDL.Nat32], [IDL.Text], ['query']),
  'revokePermissions' : IDL.Func([IDL.Nat32], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveFileMetadata' : IDL.Func([FileMetadataInput], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'uninstallApp' : IDL.Func([IDL.Nat32], [], []),
  'updateFileContent' : IDL.Func([IDL.Nat32, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpResponse = IDL.Record({
    'body' : IDL.Text,
    'headers' : IDL.Vec(HttpHeader),
    'statusCode' : IDL.Nat16,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : IDL.Int,
    'darkMode' : IDL.Bool,
    'cycles' : IDL.Nat,
    'updatedAt' : IDL.Int,
  });
  const FileMetadata = IDL.Record({
    'url' : IDL.Text,
    'name' : IDL.Text,
    'size' : IDL.Nat,
    'mimeType' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const SystemStats = IDL.Record({
    'osVersion' : IDL.Text,
    'simulatedCyclesBalance' : IDL.Nat,
    'totalInstalledApps' : IDL.Nat,
    'systemTime' : IDL.Int,
  });
  const PermissionUpdateRequest = IDL.Record({
    'permissions' : IDL.Vec(IDL.Text),
    'appId' : IDL.Nat32,
  });
  const PermissionGrantView = IDL.Record({
    'permissions' : IDL.Vec(IDL.Text),
    'grantedAt' : IDL.Int,
    'appId' : IDL.Nat32,
  });
  const AppInfo = IDL.Record({
    'id' : IDL.Nat32,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const FileType = IDL.Variant({ 'file' : IDL.Null, 'folder' : IDL.Null });
  const FileNodeView = IDL.Record({
    'id' : IDL.Nat32,
    'content' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'parentId' : IDL.Opt(IDL.Nat32),
    'nodeType' : FileType,
  });
  const ProcessSummary = IDL.Record({
    'startTime' : IDL.Int,
    'appId' : IDL.Nat32,
    'appName' : IDL.Text,
    'memoryUsage' : IDL.Nat,
    'cyclesUsed' : IDL.Opt(IDL.Nat),
  });
  const FileMetadataInput = IDL.Record({
    'url' : IDL.Text,
    'name' : IDL.Text,
    'size' : IDL.Nat,
    'mimeType' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createApp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat32], []),
    'createFile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat32)],
        [IDL.Nat32],
        [],
      ),
    'createFolder' : IDL.Func([IDL.Text, IDL.Opt(IDL.Nat32)], [IDL.Nat32], []),
    'deleteFileByUrl' : IDL.Func([IDL.Text], [], []),
    'deleteNode' : IDL.Func([IDL.Nat32], [], []),
    'fetchUrl' : IDL.Func([IDL.Text], [HttpResponse], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCyclesBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getFileMetadata' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
    'getGrantedPermissions' : IDL.Func(
        [IDL.Nat32],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getOSVersion' : IDL.Func([], [IDL.Text], ['query']),
    'getPrincipalAsText' : IDL.Func([], [IDL.Text], ['query']),
    'getSystemStats' : IDL.Func([], [SystemStats], ['query']),
    'getSystemTime' : IDL.Func([], [IDL.Int], ['query']),
    'getTotalStorageBytesUsed' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantPermissions' : IDL.Func([PermissionUpdateRequest], [], []),
    'installApp' : IDL.Func([IDL.Nat32], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'kvDelete' : IDL.Func([IDL.Text], [], []),
    'kvGet' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'kvKeys' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'kvSet' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'listAllGrantedPermissions' : IDL.Func(
        [],
        [IDL.Vec(PermissionGrantView)],
        ['query'],
      ),
    'listAvailableApps' : IDL.Func([], [IDL.Vec(AppInfo)], ['query']),
    'listChildren' : IDL.Func(
        [IDL.Opt(IDL.Nat32)],
        [IDL.Vec(FileNodeView)],
        ['query'],
      ),
    'listRunningProcesses' : IDL.Func(
        [IDL.Vec(IDL.Nat32)],
        [IDL.Vec(ProcessSummary)],
        ['query'],
      ),
    'listUserInstalledApps' : IDL.Func([], [IDL.Vec(AppInfo)], ['query']),
    'readFile' : IDL.Func([IDL.Nat32], [IDL.Text], ['query']),
    'revokePermissions' : IDL.Func([IDL.Nat32], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveFileMetadata' : IDL.Func([FileMetadataInput], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'uninstallApp' : IDL.Func([IDL.Nat32], [], []),
    'updateFileContent' : IDL.Func([IDL.Nat32, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };